import { TutorialEngine } from "@/tutorial/TutorialEngine";
import { createTourFromFlow } from "@/tutorial/createTour";
import uploadFlow from "@/tutorial/flows/upload.flow.json";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const tours = [createTourFromFlow(uploadFlow)];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TutorialEngine>{children}</TutorialEngine>
      </body>
    </html>
  );
}
